
name: Release
on: 
  push:
    branches: [ main ]
    tags-ignore:
      - '*'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Create a Release
      uses: vitalii-gdi/Github-Release-Action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs:
      - integration-test
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }} # for pushing to protected branch
      - name: Publish new version
        run: |
          git config --global user.email "no_reply@gohr.digital"
          git config --global user.name "Release Bot"
          git tag -fa v5 -m "Update v5 tag"
          git push origin v5 --force
